### ISSUE TITLE
'repeat' conflicts with Kotlin's implementation, even when import specified [Help wanted]

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/twilight#15]
See this post in the LearnSpigot Discord server
https://ptb.discord.com/channels/397526357191557121/1148658659811918024 (discord.gg/learnspigot)

We could not come to a conclusion on why it's happening or what we could do to fix it. So creating this issue for future visibility.

**Comment by Dawsson** [comment]
thoughts on changing `fun repeat` to `fun repeatingTask` ? Should fix issues

**Comment by stephendotgg** [comment]
This is a tough decision. Because if you import our repeat function, there are no issues for the average user. Only one or two people have had this issue which suggests this isn't the API's fault. Until we figure out the discrepency there isn't really more we can conclude

i think a good compromise would be to also offer a second function as you say, but not remove the original one? This will work for everyone

**Comment by Dawsson** [comment]
Yea that works, I know ive had the issue in the past

**Comment by stephendotgg** [comment]
sounds good, if the next person in twilight can just copy the repeating tasks and rename them then everyone will be happy

**Comment by Dawsson** [comment]
can we make the repeatingTask use our own `repeat` method or does that need to be recreated too?

**Comment by stephendotgg** [comment]
> can we make the repeatingTask use our own `repeat` method or does that need to be recreated too?

Lol depends if twilight is gonna suffer from this issue..... maybe play it safe & don't. Cant hurt
