### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by DevBlokJochem** [flytegg/twilight#38]
When I right click a random block, I get this error: https://paste.learnspigot.com/ikosejabar.rb

**Comment by Dawsson** [comment]
Are you shadowing? not a clue why it would be needed

**Comment by DevBlokJochem** [comment]
yep, this is my build.gradle: https://paste.learnspigot.com/axagidemax.py

**Comment by DevBlokJochem** [comment]
Fix: use 1.20 instead of 1.19 because of a new api function.
