### ISSUE TITLE
[question] how to open a gui

### ISSUE THREAD

**Issue by Cooperzilla** [flytegg/twilight#71]
Hi, i've made a gui with this but my plugin won't compile 

i'm getting this error from my ide

None of the following functions can be called with the arguments supplied.
openInventory(Inventory) defined in org. bukkit. entity. Player
openInventory(InventoryView) defined in org. bukkit. entity. Player

and this error from gradle

None of the following candidates is applicable:
fun openInventory(p0: @NotNull() Inventory): @Nullable() InventoryView?
fun openInventory(p0: @NotNull() InventoryView): Unit

and even trying the examples in the readme doesn't work and i get the same errors

**Comment by MLGPenguin** [comment]
Could you share a screenshot of the type you've provided?

**Comment by Cooperzilla** [comment]
> Could you share a screenshot of the type you've provided?

the type the gui function outputs and what im putting into player.openInventory is
gg.flyte.twilight.gui.GUI

**Comment by MLGPenguin** [comment]
You need to import gg.flyte.twilight.gui.GUI.openInventory or gg.flyte.twilight.gui.openInventory
I'm not sure which but it's one of those

**Comment by Cooperzilla** [comment]
oh ok thank you
